### ISSUE TITLE
Documentation for usage and specification of @baselineprotocol/types

### ISSUE THREAD

**Issue by skarred14** [eea-oasis/baseline-roadmap#125]
## Overview

With v0.1 release of the baseline protocol, a new package `@baselineprotocol/types` was introduced along with a reference implementation of its usage with a basic protocol for the message structure as an example type.

As a developer user, I need documentation on how to create a new type and/or use and extend existing types of messages. In particular, how is a defined protocol message used along with some examples, helps understand creating new types of specs for different types of messages. Potential example spec for a specific business process: a procurement oriented PO, or Invoice, etc.

Estimated timeline: 10/19

### Reference

- https://github.com/ethereum-oasis/baseline/tree/master/core/types
- https://github.com/ethereum-oasis/baseline/tree/master/examples/bri-1/base-example

### Acceptance

- Documentation or swagger type interface documentation for the individual types
- Documentation for additional considerations, and integration patterns for usage with @baselineprotocol/messaging

## Tasks

- [ ] docs update: how to use and extend types
- [ ] docs update: additional considerations related to specific business processes

**Comment by marcotbadur** [comment]
This should help to get a conversation going;

For OpsChain Network Procurement we are currently sending the following document types and data fields;

- RFQ: RFQ ID, Quotation deadline, material, material description, business partner(s) name
- Proposal: Quotation deadline, material, material description, and net price(s) for up to 3 tiers
- Contract: Contract ID, business partner, contract start date, contract end date, material, material, quantity, net price for each tier
- Purchase Order: PO ID, Business Partner, Contract ID, delivery date, material, material description, quantity, net price
- Invoice: Invoice ID, PO ID, business partner, invoice date, due date, material, material description, quantity, net price

We are currently not following an EDI standard but have ensured that the data fields are named in a way that is consistent with major ERP instances like SAP, so that we can utilize existing data mapping packages. The team had initial discussions around using the GS1 EDI standard but I am curious to see if there are other suggestion out there that the community has been exploring?
