### ISSUE TITLE
Phone Book

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#133]
## Project Description
This master epic contains the work involved in research and implementation of a production registry of entities that are equipped to baseline with (and who wish to be discoverable).

The baseline protocol allows a group of Parties to manually set up an [OrgRegistry](https://github.com/ethereum-oasis/baseline/blob/5fdc2becdf52000317aa83889ddb22dcf3692b86/core/contracts/contracts/OrgRegistry.sol) contract. The OrgRegistry does not really define the workgroup in the v0.1 protocol, though it did in the original "radish34" demo from 2019. Since v0.1, the Shield contract and the Workflow itself enforce who is in a particular Workgroup. This allows for the development of a universal OrgRegistry, presumably deployed on the Ethereum Mainnet as a public registry -- a "phone book" (or yellow pages, more precisely) of baselined counterparties.

Clearly, in order for a universal phone book to be safe and effective, it requires additional attributes beyond what is required of an OrgRegistry instance that handles only a known and closely managed single Workgroup.  Discovering, specifying, and architecting (possibly building initial code) of these attributes is the job of this Epic.

## Impact on the Baseline Community
Every baselined Workflow needs to know what counterparties are allowed to sign a Workstep. That set of counterparties is called the Workgroup. A Workgroup can be set up manually by getting the counterparties together and deploying an OrgRegistry contract specifically for a particular Workflow, but this has the downside of requiring counterparty education and a load of organizational setup work each time a Workflow is developed. And it has the long-term downside of lacking reuse -- a company that is already baselining with one Workgroup must repeat the manual setup on a new OrgRegistry to sign Worksteps in another group. It would be nice if someone setting up a Workflow could search for the counterparties they want to work with in a "Yellowpages" of baselined company listings and then simply invite them to the new Workgroup. However, unlike the manual process of setting up a specific OrgRegistry with known counterparties, if an organizer selects a party from a standing registry -- a "phone book" -- then the organizer will need to be sure the listing is authentic, that the company (and department, and particular system, and people) the organizer wishes to interact with is actually behind the listing and that there are no errors in attributes such as messaging endpoints or blockchain accounts that could potentially cause data, for example, to be sent to the wrong entity or group. 

## Acceptance criteria and must have scope
The Phone Book must adhere to the security, performance and other NFR standards being written by the specifications team.
The Phone Book does not need to be a full-blown "decentralized identity" solution, and while it should define how sub-domains for internal corporate organizations work, and how user management and permissions are handled, the "yellow pages" entry itself does not need to implement such things as self-sovereign identities for users. Ideally, it would also not require entities to manage blockchain wallets (at least not in the way one might as a cryptocurrency hodlr would).

## Timeline
Security spikes must be completed and general agreement achieved before a Phone Book can be deployed. Given that we wish strongly to have such a phone book on the Mainnet by 2021, the research and decision-making about things like DID, Verifiable Credentials (W3C), authentication authorization, root of trust, person of authority, etc. is a high priority and immediate piece of work. That said, it would be acceptable if such issues are covered exogenously via integration with enterprise cloud accounts, where the initial universal phone book instance is restricted to parties that initiate a listing using cloud account credentials and integration.

---

[Background](https://help.zenhub.com/support/solutions/articles/43000010341) on Epics, Issues, Checkboxes (aka, Epics, Stories, Tasks)

After you start breaking this master epic up into a set of Issues (sub-epics, stories, tasks, etc), you might consider creating a Project in Github to make it easy for your group to have a single Kanban board for just this work. The Github projects tab in any given repo will allow only Issues from that repo, but if you create one [here](https://github.com/orgs/ethereum-oasis/projects), you will be able to set up a project that can compose Issues from any of the baseline repos, including the core /baseline repo and the planning /baseline-roadmap repo.

**Comment by KirkBallou** [comment]
@humbitious Story Idea for the Challenge:
White label enterprise DIDs to edit their specific org contacts. If the DID submitting is not in the white list the submission is rejected.
Example: Coca-Cola DID can edit their specific org. So you have a multi-org phonebook where each org has rights to their specific segment.

**Comment by brantlymillegan** [comment]
I highly recommend that Baseline uses ENS for this. ENS already works, is widely used, and is compatible with DNS (the original "phone book of the Internet"). No need to reinvent the wheel. I'm signed up for the event to discuss.

**Comment by chaals** [comment]
ENS is one useful part of an overall approach to authenticating, but you need to know that a particular ENS registered name (like a domain name) actually corresponds to the organisation you think it does. (Because domain names are explicitly temporarily assigned, if the owner changes, reliance on DNS becomes a guarantee of failure. Likewise, substituting a Domain Name Server is feasible and can cause the same problems.)

The [Organization Registry](https://entethalliance.github.io/client-spec/chainspec.html#sec-identifying-organizations) in the EEA's [Permissioned Blockchains spec](https://entethalliance.github.io/client-spec/chainspec.html) is designed to solve the problem of ensuring that a known organisation is identified as being responsible for its actions.

More particularly, it is

> a smart contract based registry, to provide on-chain validation that a particular Ethereum accounts or nodes is owned by a participating organization in an Enterprise Ethereum blockchain.

that would happily work on Ethereum mainnet.

It doesn't solve the complete identity problem (how do you know that something is "The ACME road-runner-trap company" that you meant, not some other company of the same name), but if you have some identifier that you trust as being from the organisation you are looking for, it can provide a framework to connect that to actions or accounts on a chain.

cc @jimthematrix who made the initial proposal.

**Comment by humbitious** [comment]
@brantlymillegan @chaals -- Great input here. Johnny Howle, Evin McMullen, @caleteeter and others have been holding design sessions leading up to this. Reach out to them on the Slack workgroup, and they can invite you. 

For my part, I'd be happy to see the phonebook populated by companies directly from their cloud accounts, using their cloud credentials and control systems that are already in place (e.g., enterprise cloud account already confirms that a company holds its web domain, and it has mature systems for ensuring that there are appropriate approvals up and down the corporate hierarchy to ensure that if, for example, a department manager initiates a process like creating a baselining phonebook (yellow pages, really) entry, the top level administrator for the company is aware and approves).  As Brantley pointed out, there is little reason right now to reinvent the wheel. User management and approval workflows are a done thing in enterprise cloud accounts. Seems like a good bootstrapping approach, even though that would -- and I for one am totally fine with this, though it is up to the community -- limit registrations to the phonebook to companies that have cloud accounts that implement for baseline.

**Comment by ethevin** [comment]
@chaals @brantlymillegan Thank you for these notes - absolutely part of our conversation so far. We look forward to joining you in conversation (or async communication!) in the coming days. Please reach out on slack in the phone book channel.

**Comment by brantlymillegan** [comment]
@humbitious Can you email me a link to the Slack channel? (brantly@ens.domains)

@chaals Yes, the organization registry could specify that an organization owns a particular ENS name. Re ENS names being temporarily owned, that can be solved by registering names for extended periods of time (e.g. 100 years; you can pay ahead in ENS). To save on costs, we could even get one ENS name, e.g. baseline.eth, then issue subdomains off of that (that way onlly baseline.eth has to be paid to be registered for 100 years, as subdomains have no fee and are unlimited).

**Comment by italobb** [comment]
My team (the Identity Team from [Consensys Mesh](https://mesh.xyz/)) have been working in a solution based in the use of [.well-known DID configuration](https://identity.foundation/specs/did-configuration/) from the [DIF](https://identity.foundation/) (an [RFC5785](https://tools.ietf.org/html/rfc5785) specialization) as the trust anchor between the company [DIDs](https://www.w3.org/TR/did-core/) and its web domain (commonly trusted by enterprises).

In a few words, the _.well-known DID configuration_ is a file stored in a well known path of an website, which contains a list of signed VCs linking their issuer DID to the domain of the same website where it is stored.

This approach allow the owner of some DID to prove they can act (sign) on behalf of the company (because only the owner of the company website is capable of setting this association up) without the need of an intermediary issuing this proof. This turns the phonebook host into a simple registry holder, removing some strong responsibilities from it like guaranteeing the company identity or being accountable for any damage originated from tampered data.

This solution can be extended by associating to each phonebook entry VCs issued by third parties, regulators or any other trusted party elected by some ecosystem. You can even have some entity assuming some accountability over the catalog governance, if it's interesting for an specific ecosystem. Those VCs can be used to improve trust on each entry or to allow the implementation of any other business rule based in credentials attributes.

Multiple phone books can co-exist using the same base solution, just differentiating each other by the phonebook host, which can decide who will be listed based in its own criteria, or by the way VCs are associated to entries.

We'll be sharing something soon. Happy to hear any feedback about this approach.

**Comment by Arachnid** [comment]
> ENS is one useful part of an overall approach to authenticating, but you need to know that a particular ENS registered name (like a domain name) actually corresponds to the organisation you think it does. (Because domain names are explicitly temporarily assigned, if the owner changes, reliance on DNS becomes a guarantee of failure. Likewise, substituting a Domain Name Server is feasible and can cause the same problems.)

One option that may work for you here is to make the OrgRegistry an ENS registrar. That is, it would own an ENS name, and follow whatever built-in logic it has for issuing subdomains to individual organisations. It can also, if desired, control the resolution of those names, to include whatever DIDs or other fields are required.

That way, anyone wanting to resolve organisations can use the same infrastructure used today for ENS, while having any assurances provided by the registry as to the identity and veracity of the organisations it's resolving.
