### ISSUE TITLE
Tokenization and Asset Management of Invoices and other Baselined Records

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#17]
Now that we have shown master service agreements (MSA) and purchase orders (PO) baselined in the Radish34 demo, it is time to take the next step and show invoices following from purchase orders (and other events). This will likely lead to the requirement for a workstep to validate not on simply one previous workstep (e.g., PO on MSA) but on several, including a workstep where a delivery receipt workstep has successfully completed. This will also increase the intensity on prioritizing other projects such as #59 and #58, because a longer string of baselined worksteps will have more risk of failure from record changes.

Here's a picture of the progression of mini-projects on the way to this major tentpole of Summer 2020 for the baseline community.

Note in this picture the progression from specific demos to generalizations.

![image](https://user-images.githubusercontent.com/1388686/83980464-14036c80-a8e4-11ea-92ab-f851740b1ab2.png)

**Comment by humbitious** [comment]
![Tokenization Discussion Notes](https://user-images.githubusercontent.com/1388686/82688861-96730780-9c27-11ea-875f-60441a849d83.png)

**Comment by humbitious** [comment]
![Tokenization without tokenization conjecture](https://user-images.githubusercontent.com/1388686/82689041-dc2fd000-9c27-11ea-895f-724994cf5b64.png)

**Comment by humbitious** [comment]
Initial conversation with Kartheek May 21, 2020:
https://consensys.zoom.us/rec/share/6-5cLLTup0JIUqvfyG_GYpEOJI7JT6a81nUZ-fZen01HY5jgNlnxU_639tI4AUBp Password: 4M%91cp*

**Comment by humbitious** [comment]
Initial meeting on tokenization with a dozen baseline members, led by Kartheek.

https://consensys.zoom.us/rec/share/5MJtdK368GpIaYH141D6c4o5P7naX6a8gylK8_Rbz0gZIkUtbxGLVmVtoccZ8NWn Password: 5I@4&@&3

**Comment by sambacha** [comment]
https://github.com/freight-chain/factoring

- accepts a proof of delivery (bill of lading upon delivery)
- ability to auction off your proof of delivery (i.e. commercial invoice)

InvoiceTap is the specific contract in that repo, that entire stack is being depreciated in our next release and has not been audited. 

UCC form 1 integration for U.S. accounts receivable financing is the only issue, our workaround is currently utilizing lendflow.io which is why we dont do this on-chain. The industry is very much relationship-based, as your factoring company has a lien against your company, it does not provide for you to "shop" around actually, so it wasn't viable to pursue us at the time. Also this type of financing is a "US" thing, as corporations typically financed through the bond market, whereas elsewhere a more traditional bank loan is used. LiquidX would be the biggest game in town for accounts receivable financing.

**Comment by humbitious** [comment]
Tranching the invoices might be considered as a step in the proposed process.

**Comment by danielnorkin** [comment]
Adding @Blockjock47 to assist with token definitions, behaviors, etc.

**Comment by danielnorkin** [comment]
@skarred14 @dlefloch @sambacha @humbitious - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
