### ISSUE TITLE
Create/Run Monthly Community Event

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#29]
It's clear that the baseline community needs to have a regular monthly and/or quarterly general session. What is not clear is what the goal and format of the meeting should be:

1. Could be to encourage and attract new members (celebrate progress, etc...more)
2. Could be to vet issues
3. Could be an "ask me anything" for members

Acceptance criteria:

[ ] Regular webinar meeting scheduled
[ ] Hundreds attend
[ ] We know what we intend to provide attendees, and they report that they got it.

**Comment by Sjaaaakster** [comment]
We have the baseline business hours for several weeks on Wednesday.

I see that the popularity is increasing on social media.

We could expand this with special guests, themes and other things.

Let Baseline Business hours grow into something that everyone is looking forward to.

Things to investigate further

What is the target group?

What are themes?

Should we look for a host? Or is John Wolpert willing to continue to do this?

Schedule broadcasts / guests / topics 2 weeks in advance so that targeted posts can be posted on social media to attract more viewers.
