### ISSUE TITLE
Standards and Specifications Writing Master Epic

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#99]
As the Init-Core branch merge approaches, which is the first example of serious abstraction and generalization of the baseline protocol from the radish34 demo, it is time to start organizing the articulation of the patterns into "cookbooks," specifications, and ultimately standards.  As a part of the OASIS family, the baseline protocol has access to terrific resources not only for helping us structure best practices around this work but also to codify it and ultimately promulgate it through OASIS (and potentially the standards bodies that OASIS works with -- ISO, IEC, W3C, IEEE, ITU -- as appropriate).  

Originally, we had a set of specific epics under the roadmap grouping around standards, but as we mature, it becomes clear that having a top level epic that contains the others is more optimal.

Please add standards/specifications epics and issues under this one.

**Comment by Consianimis** [comment]
I am interested in understanding the high level structure of the specifications and what is the current view of what should be included in the Oasis standard.  Is the attached more or less correct?
![BaselineProtocolSpecifications - High Level Structure](https://user-images.githubusercontent.com/8512677/89731964-31b79400-da43-11ea-8663-fd0ccbab793c.JPG)

**Comment by danielnorkin** [comment]
I like where you are coming from. Can you help define your view of core
specs vs other specs?

**Comment by Consianimis** [comment]
I would define core specifications as the building blocks/cornestones of the Baseline Protocol (i.e. if those things are not there, it won't work).
- protocol specs: the approach itself, its design and its implementation
- mainnet specs: the definition and features of a viable public mainnet (I do not know if this is correct but in my head, no mainnet = no baseline protocol)

I would define others specs as optional or extending core specifications. 
From a documentation perspective, we may not need to produce them but it could be helpful to the community if they exist:
- clients specs: I was thinking here about generic clients specs (but could be CRM-client specs, ERP-client specs). One question is can protocol specs be used as generic client specs ?
- industry specs: when developing use cases, maybe there will be industry specific requirements and considerations that will emerge and will need to be acknowledged ? If we have enough learnings, maybe it will help adoption across key industries to produce those specs.

**Comment by chaals** [comment]
This looks like about the right approach. On particular, I would start by writing the generic explanation of how it works, and then identifying and writing down the bits that any two organisations need to do so they can make it work without any other prior agreement. So that might include stuff that is very specific to the Ethereum main net, or you might find that it's already easy enough to specify it in a way that allows changing the "main net" (if you want).

**Comment by Consianimis** [comment]
That makes sense. For now, I have a bias towards holding a blockchain-agnostic view to the mainnet specs. If there is no abstraction layer or anything designed to manage interoperability then it would read as 'Baseline protocol for Ethereum Mainnet' specs.
The question is - if another blockchain matches the requirements in Mainnet Specs, would they be able to implement the Protocol specs and therefore support baselining in their ecosystem?  If the answer is no because protocol specs are tied to Ethereum mainnet then blockchain-agnostic view to the mainnet specs becomes invalid.

**Comment by chaals** [comment]
I would start the other way around, with a concrete bias for Ethereum (among other reasons, because that's the core focus of the Ethereum OASIS project). That way we have a clear proof that it works, rather than starting out designing for a theoretical possibility of changing the baseline network.

**Comment by Consianimis** [comment]
Ah thank you, this is helpful as it clarifies things on my side.  In that case, it seems more appropriate to think of it as  'Baseline protocol for Ethereum Mainnet' specs rather than 'Baseline protocol for public Mainnet' specs (with Ethereum implementation as proof that it works).

**Comment by Consianimis** [comment]
@chaals - https://github.com/ethereum-oasis/baseline/issues/115 suggests that the protocol specs should not single out Ethereum as the only public mainnet implementation. What do you think ?

**Comment by danielnorkin** [comment]
My personal take on what Chaals said was to use public Eth Mainnet as a
reference or a starting point. That may give other public ledgers specs to
follow if they want to be considered as a mainnet that fits with
baselining.

I dont think he ment that it should be the "only" mainnet.

**Comment by Consianimis** [comment]
@danielnorkin, @chaals - Thank you, your feedback helps a lot. I understand better now.
